# Generated by Django 3.0.7 on 2020-06-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
