# Generated by Django 3.0.7 on 2020-06-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_auto_20200616_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='novalid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
