# Generated by Django 3.0.7 on 2020-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_auto_20200616_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finish',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='novalid',
            field=models.BooleanField(default=False),
        ),
    ]
