# Generated by Django 3.0.7 on 2020-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
